version = 0.1
[default.deploy.parameters]
stack_name = "comparador-avanti-lambda"
resolve_s3 = true
s3_prefix = "comparador-avanti-lambda"
region = "us-east-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
image_repositories = []
