# @format

AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  SAM Template comparador-avanti-lambda
Globals:
  Function:
    Timeout: 3

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/hello-world/
      Handler: app.lambdaHandler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      MemorySize: 128
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /hello
            Method: get

  PlanoFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/plano/
      Handler: app.lambdaHandler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      MemorySize: 128
      Policies:
        # Acesso Create/Read/Update/Delete para tabela Plano
        - DynamoDBCrudPolicy:
            TableName: !Ref Plano
      Environment:
        Variables:
          # Expõe o nome da tabela do DynamoDB como variável de ambiente
          PlanoTable: !Ref Plano
      Events:
        Plano:
          Type: Api
          Properties:
            Path: /planos
            Method: get
  Plano:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: id
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2

  CargaInicialFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/carga-inicial/
      Handler: app.lambdaHandler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      MemorySize: 128
      Policies:
        # Acesso Create/Read/Update/Delete para tabela Plano
        - DynamoDBCrudPolicy:
            TableName: !Ref Plano
      Environment:
        Variables:
          # Expõe o nome da tabela do DynamoDB como variável de ambiente
          PlanoTable: !Ref Plano

  CargaInicialResource:
    Type: "Custom::MyCustomResource"
    Properties:
      ServiceToken: !GetAtt CargaInicialFunction.Arn

Outputs:
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn
  PlanoApi:
    Description: "API Gateway endpoint URL for Prod stage for Plano function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/planos  /"
  PlanoFunction:
    Description: "Plano Lambda Function ARN"
    Value: !GetAtt PlanoFunction.Arn
  PlanoFunctionIamRole:
    Description: "Implicit IAM Role created for Plano function"
    Value: !GetAtt PlanoFunctionRole.Arn
  CargaInicialResponse:
    Description: Data From Lambda Carga Inicial
    Value: !GetAtt CargaInicialResource.cargaFeita
